import React, {useEffect, useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";
import {MirrorSetup} from "./mirror-setup";
import {InstanceBrand, type Instance} from "./instance-brand";

type Span={start_line:number;end_line:number};
type Entity={handle:string;kind:string;label:string;identity:string;repository:string;path:string;generation:string;evidence:string;confidence:number;evidence_count:number;span:Span};
type Claim={handle:string;subject:string;object:string;predicate:string;evidence:string;confidence:number;derivation:string};
type Projection={repository:string;generation:string;nodes:Entity[];edges:Claim[];truncated:boolean};
type Status={projection_state:string;repositories:{id:string;generation:string;revision:string;active:boolean}[];projections?:{kind:string;state:string;source_generation:string;fingerprint:string;record_counts?:Record<string,number>}[]};
let csrf="";
const request=async<T,>(path:string,body?:unknown):Promise<T>=>{const r=await fetch(path,{method:body?"POST":"GET",credentials:"same-origin",headers:body?{"Content-Type":"application/json","X-CSRF-Token":csrf}:undefined,body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error((await r.json().catch(()=>({error:"request failed"}))).error);return r.json()};
function App(){const [showSetup,setShowSetup]=useState(false);const [instance,setInstance]=useState<Instance>();const [status,setStatus]=useState<Status>();const [projection,setProjection]=useState<Projection>();const [selected,setSelected]=useState<Entity>();const [evidence,setEvidence]=useState<{path:string;start_line:number;end_line:number;lines:string[];truncated:boolean}>();const [query,setQuery]=useState("");const [notice,setNotice]=useState("");const load=async()=>{const s=await request<Status>("/api/v1/status");setStatus(s);setInstance(await request<Instance>("/api/v1/instance"));const repo=s.repositories.find(r=>r.active);if(repo){setProjection(await request<Projection>(`/api/v1/projection?repo=${encodeURIComponent(repo.id)}`))}};useEffect(()=>{const token=new URL(location.href).hash.match(/token=([^&]+)/)?.[1];history.replaceState(null,"","/");if(!token){setNotice("This secure launch link has expired.");return}fetch("/api/v1/session",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}).then(async r=>{if(!r.ok)throw new Error("Unable to securely connect.");csrf=(await r.json()).csrf_token;return load()}).catch(e=>setNotice(e.message))},[]);
 const brand=instance&&<InstanceBrand instance={instance} onSave={async v=>setInstance(await request<Instance>("/api/v1/instance",v))}/>;
 const inspect=async(entity:Entity)=>{setSelected(entity);setEvidence(undefined);try{setEvidence(await request("/api/v1/evidence",{evidence:entity.evidence,before:2,after:2,max_lines:40}))}catch(e){setNotice(e instanceof Error?e.message:"Evidence unavailable")}};
 const search=async(e:React.FormEvent)=>{e.preventDefault();try{const r=await request<{status:string;entities:Entity[];trace:{kind:string;detail:string;handle?:string;rank?:number}[];truncated:boolean}>("/api/v1/query",{text:query,repository:projection?.repository,limit:20});setNotice(r.status==="not_found"?"No active-generation evidence matched this query.":r.truncated?"Results are bounded; refine the query for more evidence.":"");if(r.entities[0])await inspect(r.entities[0])}catch(x){setNotice(x instanceof Error?x.message:"Query unavailable")}};
 if(notice&&!status)return <main><h1>Repository knowledge</h1><p role="alert">{notice}</p></main>;
 if(!status)return <main><p>Opening local knowledge…</p></main>;
 if(status.projection_state==="no_active_generation")return <main>{brand}<h1>No active generation</h1><p>No repository checkout has been changed.</p><MirrorSetup request={request} onReady={load}/></main>;
 if(status.projection_state==="unavailable")return <main>{brand}<h1>Knowledge is safe</h1><p>The map projection is unavailable. Canonical source evidence remains intact; run <code>projections rebuild</code> locally.</p></main>;
 return <main>{brand}<header><p>Read-only repository knowledge</p><h1>Knowledge map</h1><button onClick={()=>void load()}>Refresh</button><button onClick={()=>setShowSetup(!showSetup)}>Repository setup</button></header>{showSetup&&<MirrorSetup request={request} onReady={load}/>} {notice&&<p role="status">{notice}</p>}<form onSubmit={search}><label>Query <input value={query} onChange={e=>setQuery(e.target.value)} /></label><button>Search</button></form><p>{projection?.repository} · generation {projection?.generation} · {projection?.nodes.length||0} nodes · {projection?.edges.length||0} evidence-backed edges{projection?.truncated?" · bounded projection":""}</p><section aria-label="Knowledge graph"><h2>Entities</h2><ul role="listbox" aria-label="Select visible graph node">{projection?.nodes.map(n=><li key={n.handle}><button onClick={()=>void inspect(n)} aria-pressed={selected?.handle===n.handle}>{n.label}</button> <small>{n.kind} · {n.confidence.toFixed(2)} confidence · {n.evidence_count} claims</small></li>)}</ul><h2>Relationships</h2><ul>{projection?.edges.map(e=><li key={e.handle}>{e.predicate} · {e.confidence.toFixed(2)} · {e.derivation}</li>)}</ul></section><aside aria-label="Evidence inspector"><h2>{selected?.label||"Select an entity"}</h2>{selected&&<p>{selected.repository}/{selected.path} · generation {selected.generation} · lines {selected.span.start_line}–{selected.span.end_line}</p>}{evidence&&<pre>{evidence.lines.join("\n")}</pre>}</aside></main>}
createRoot(document.getElementById("root")!).render(<App/>);
