import React, {useEffect, useRef, useState} from "react";
type Repo = {id:string; url:string; ref:string; include:string; exclude:string};
export type Setup = {mode?:string; state:string; error?:string; completed_repositories:number; repositories?:Repo[]; local_repositories?:{id:string;path:string}[]; rules?:Record<string,{include?:string[];exclude?:string[]}>};
type Preview = {valid:boolean; repositories:{id:string;valid:boolean;error?:string;files:number;languages:string[];frameworks:string[];exclusions:Record<string,number>}[]};
const empty = ():Repo => ({id:"",url:"",ref:"refs/heads/main",include:"",exclude:""});
const patterns = (text:string) => text.split(",").map(x=>x.trim()).filter(Boolean);
export function MirrorSetup({request,onBuild}:{request:<T>(path:string,body?:unknown)=>Promise<T>;onBuild:()=>void}) {
  const [mode,setMode]=useState("mirror"),[repos,setRepos]=useState<Repo[]>([empty()]);
  const [preview,setPreview]=useState<Preview>(),[job,setJob]=useState<Setup>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const userSelectedMode=useRef(false);
  useEffect(()=>{let live=true;request<Setup>("/api/v1/onboarding").then(s=>{if(!live)return;setJob(s);if(!userSelectedMode.current){setMode(s.mode==="local"?"local":"mirror");const entries=s.mode==="local"?s.local_repositories?.map(r=>({id:r.id,url:r.path,ref:"refs/heads/main"})):s.repositories;if(entries?.length)setRepos(entries.map(r=>({...r,include:(s.rules?.[r.id]?.include||[]).join(", "),exclude:(s.rules?.[r.id]?.exclude||[]).join(", ")})))}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);
  const body=()=>({mode,rules:Object.fromEntries(repos.map(r=>[r.id,{include:patterns(r.include),exclude:patterns(r.exclude)}])),...(mode==="local"?{local_repositories:repos.map(r=>({id:r.id,path:r.url}))}:{repositories:repos.map(({id,url,ref})=>({id,url,ref}))})});
  const edit=(next:Repo[])=>{setRepos(next);setPreview(undefined)};
  async function validate(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setPreview(undefined);try{setPreview(await request<Preview>("/api/v1/onboarding/preview",body()))}catch(e){setError(e instanceof Error?e.message:"Preview failed")}finally{setBusy(false)}}
  async function build(){setBusy(true);setError("");try{await request("/api/v1/onboarding/configure",body());await request("/api/v1/onboarding/start",{});onBuild()}catch(e){setError(e instanceof Error?e.message:"Build failed")}finally{setBusy(false)}}
  return <section aria-label="Repository setup"><h2>Connect approved Git sources</h2><label>Source type<select aria-label="Source type" value={mode} disabled={busy} onChange={e=>{userSelectedMode.current=true;setMode(e.target.value);edit([empty()])}}><option value="mirror">Mirror: managed Git snapshots</option><option value="local">Direct: current local working trees</option></select></label><p>Choose one source mode for 1–100 repositories. Direct includes eligible tracked edits and untracked files. Preview immutable source scope before Build. Machine Git credentials stay outside AgentOS.</p>
    <form onSubmit={validate}>{repos.map((repo,i)=><fieldset key={i} disabled={busy}><legend>Repository {i+1}</legend>{((mode==="local"?["id","url"]:["id","url","ref"]) as ("id"|"url"|"ref")[]).map(key=><label key={key}>{key==="id"?"Repository ID":key==="url"?mode==="local"?"Absolute workspace path":"Git URL or absolute remote path":"Full Git ref"}<input aria-label={`${key} ${i+1}`} required value={repo[key]} onChange={e=>edit(repos.map((r,j)=>j===i?{...r,[key]:e.target.value}:r))}/></label>)}<label>Include patterns (comma separated; blank includes all)<input aria-label={`include ${i+1}`} value={repo.include} onChange={e=>edit(repos.map((r,j)=>j===i?{...r,include:e.target.value}:r))}/></label><label>Exclude patterns (comma separated)<input aria-label={`exclude ${i+1}`} value={repo.exclude} onChange={e=>edit(repos.map((r,j)=>j===i?{...r,exclude:e.target.value}:r))}/></label>{repos.length>1&&<button type="button" onClick={()=>edit(repos.filter((_,j)=>i!==j))}>Remove repository {i+1}</button>}</fieldset>)}<button type="button" disabled={busy||repos.length>=100} onClick={()=>edit([...repos,empty()])}>Add repository</button><button disabled={busy}>{busy?"Validating sources…":"Preview scope"}</button></form>
    {preview&&<section aria-label="Scope preview"><h3>{preview.valid?"Sources validated":"Resolve source errors before Build"}</h3>{preview.repositories.map(r=><article key={r.id}><strong>{r.id}</strong>{r.valid?<p>{r.files} files · {r.languages.join(", ")||"No supported language detected"} · {r.frameworks.join(", ")||"No framework manifest detected"}</p>:<p role="alert">{r.error}</p>}<p>Exclusions: {Object.entries(r.exclusions).map(([reason,count])=>`${reason}: ${count}`).join(", ")||"none encountered"}</p></article>)}</section>}
    <button disabled={busy||!preview?.valid} onClick={()=>void build()}>{job?.state==="failed"||job?.state==="interrupted"?"Retry setup":"Sync and index"}</button>{(error||job?.error)&&<p role="alert">{error||job?.error}</p>}
  </section>;
}
export function IndexingCard({request,onReady,onRetry}:{request:<T>(path:string,body?:unknown)=>Promise<T>;onReady:()=>Promise<void>;onRetry:()=>void}) {
  const [job,setJob]=useState<Setup>(),[events,setEvents]=useState<{sequence:number;stage:string;repository:string;files:number;queryable:boolean}[]>([]),[error,setError]=useState("");
  useEffect(()=>{let live=true,finished=false;const poll=async()=>{try{const [s,a]=await Promise.all([request<Setup>("/api/v1/onboarding"),request<{events:typeof events}>("/api/v1/activity")]);if(!live)return;setJob(s);setEvents(a.events);if((s.state==="ready"||s.state==="maintaining")&&!finished){finished=true;await onReady()}}catch(e){if(live)setError(e instanceof Error?e.message:"Indexing status unavailable")}};void poll();const timer=window.setInterval(()=>void poll(),750);return()=>{live=false;window.clearInterval(timer)}},[]);
  const running=!job||job.state==="syncing"||job.state==="ingesting";
  return <section aria-label="Indexing activity"><h2>{running?"Building knowledge":job.state==="ready"?"Knowledge is ready":"Build needs attention"}</h2><p role="status">{job?.state==="syncing"?"Synchronizing approved mirrors…":job?.state==="ingesting"?`${job.completed_repositories} mirrors synchronized. Compiling snapshots…`:"Validated generations become queryable only after promotion."}</p><ul>{events.slice(-8).map(e=><li key={e.sequence}>{e.repository} · {e.stage}{e.files?` · ${e.files} files`:""} · {e.queryable?"active evidence":"progress only; not queryable"}</li>)}</ul>{running?<button onClick={()=>void request("/api/v1/onboarding/cancel",{}).catch(e=>setError(e.message))}>Cancel setup</button>:job?.state!=="ready"&&<button onClick={onRetry}>Review sources and retry</button>}{(error||job?.error)&&<p role="alert">{error||job?.error}</p>}</section>;
}
