import React,{useEffect,useState} from "react";
type Repo={id:string;url:string;ref:string};
type Setup={mode?:string;local_repositories?:{id:string;path:string}[];state:string;error?:string;completed_repositories:number;repositories?:Repo[]};
export function MirrorSetup({request,onReady}:{request:<T>(path:string,body?:unknown)=>Promise<T>;onReady:()=>Promise<void>}){
 const [mode,setMode]=useState("mirror");const [repos,setRepos]=useState<Repo[]>([{id:"",url:"",ref:"refs/heads/main"}]),[job,setJob]=useState<Setup>(),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const poll=async()=>{const status=await request<Setup>("/api/v1/onboarding");setJob(status);return status};
 useEffect(()=>{let live=true;request<Setup>("/api/v1/onboarding").then(s=>{if(live){setJob(s);if(s.mode==="local"){setMode("local");setRepos((s.local_repositories||[]).map(r=>({id:r.id,url:r.path,ref:"refs/heads/main"})))};if(s.repositories?.length&&s.mode!=="local")setRepos(s.repositories)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[]);
 useEffect(()=>{if(job?.state!=="syncing"&&job?.state!=="ingesting")return;let live=true;const timer=setInterval(()=>{poll().then(s=>{if(live&&s.state==="ready")void onReady()}).catch(e=>{if(live)setError(e.message)})},750);return()=>{live=false;clearInterval(timer)}},[job?.state]);
 const start=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await request("/api/v1/onboarding/configure",mode==="local"?{mode,local_repositories:repos.map(r=>({id:r.id,path:r.url}))}:{mode,repositories:repos});setJob(await request<Setup>("/api/v1/onboarding/start",{}))}catch(e){setError(e instanceof Error?e.message:"Setup failed")}finally{setBusy(false)}};
 const running=busy||job?.state==="syncing"||job?.state==="ingesting";
 return <section aria-label="Repository setup"><h2>Connect approved Git sources</h2><label>Source type<select aria-label="Source type" value={mode} disabled={busy||job?.state==="syncing"||job?.state==="ingesting"} onChange={e=>{setMode(e.target.value);setRepos([{id:"",url:"",ref:"refs/heads/main"}])}}><option value="mirror">Managed Git mirrors</option><option value="local">Clean local Git workspaces</option></select></label><p>Configure 1–100 repositories. Homefold compiles immutable owned snapshots. Local workspaces must be clean and committed.</p><form onSubmit={start}>{repos.map((repo,i)=><fieldset key={i} disabled={running}><legend>Repository {i+1}</legend>{((mode==="local"?["id","url"]:["id","url","ref"]) as ("id"|"url"|"ref")[]).map(key=><label key={key}>{key==="id"?"Repository ID":key==="url"?(mode==="local"?"Absolute local workspace path":"Git URL or absolute local remote path"):"Full Git ref"}<input aria-label={`${key} ${i+1}`} value={repo[key]} required onChange={e=>setRepos(repos.map((r,j)=>j===i?{...r,[key]:e.target.value}:r))}/></label>)}{repos.length>1&&<button type="button" onClick={()=>setRepos(repos.filter((_,j)=>i!==j))}>Remove repository {i+1}</button>}</fieldset>)}<button type="button" disabled={running||repos.length>=100} onClick={()=>setRepos([...repos,{id:"",url:"",ref:"refs/heads/main"}])}>Add repository</button><button disabled={running}>{job?.state==="failed"||job?.state==="interrupted"?"Retry setup":"Sync and index"}</button></form>{running&&<button onClick={()=>void request("/api/v1/onboarding/cancel",{}).catch(e=>setError(e.message))}>Cancel setup</button>}<p role="status">{job?.state==="syncing"?"Synchronizing approved mirrors…":job?.state==="ingesting"?(mode==="local"?"Capturing committed local snapshots and compiling evidence…":`${job.completed_repositories} mirrors synchronized. Compiling snapshots…`):job?.state==="ready"?"Knowledge is ready.":job?.state==="interrupted"?"Setup interrupted. Retry safely.":"Awaiting approved repositories."}</p>{(error||job?.error)&&<p role="alert">{error||job?.error}</p>}</section>
}
